#!/usr/bin/env python3
"""Embed the shared touch-control SVG set into the library.

The artwork lives once in `shared/port-assets`; a consumer embeds it at build
time so the installed product has no machine-specific asset path and no runtime
dependency on a checkout. The bytes are rasterised at the size actually drawn by
`touch_ui::Controls`, which is why the embedded unit is the vector source rather
than a bitmap.

    python3 tools/embed_svg.py --assets <port-assets> --source out.cpp --header out.h
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SET = "touch-controls"


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def glyphs(assets: Path) -> list[str]:
    manifest = assets / "sets" / SET / "set.json"
    if not manifest.is_file():
        raise SystemExit(f"embed_svg: {manifest} is missing; check PORT_ASSETS_DIR")
    names = json.loads(manifest.read_text())["glyphs"]
    if not names:
        raise SystemExit(f"embed_svg: {manifest} lists no glyphs")
    for name in names:
        if not (assets / "sets" / SET / f"{name}.svg").is_file():
            raise SystemExit(f"embed_svg: {name}.svg is missing from {manifest.parent}")
    return sorted(names)


def byte_rows(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        chunk = ", ".join(f"0x{byte:02X}" for byte in data[offset : offset + 16])
        rows.append(f"    {chunk},")
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assets", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    args = parser.parse_args()

    names = glyphs(args.assets)
    source = [
        "// Generated by tools/embed_svg.py. Do not edit.",
        '#include "embedded_icons.h"',
        "",
        "namespace touch_ui::embedded_icons {",
        "namespace {",
    ]
    entries = []
    for name in names:
        data = (args.assets / "sets" / SET / f"{name}.svg").read_bytes()
        variable = f"k{name.replace('-', '_')}"
        source.append(f"const unsigned char {variable}[] = {{")
        source.append(byte_rows(data))
        source.append("};")
        entries.append(f'    Icon{{"{escape(name)}", {variable}, {len(data)}}},')
    source.extend(
        [
            "constexpr Icon kIcons[] = {",
            *entries,
            "};",
            "",
            "} // namespace",
            "",
            "const Icon *find(std::string_view name) {",
            "  for (const Icon &icon : kIcons) {",
            "    if (name == icon.name) {",
            "      return &icon;",
            "    }",
            "  }",
            "  return nullptr;",
            "}",
            "",
            "} // namespace touch_ui::embedded_icons",
            "",
        ]
    )
    header = [
        "// Generated by tools/embed_svg.py. Do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <string_view>",
        "",
        "namespace touch_ui::embedded_icons {",
        "",
        "struct Icon {",
        "  const char *name;",
        "  const unsigned char *bytes;",
        "  unsigned size;",
        "};",
        "",
        "// The glyph with this name, or nullptr. Names come from port-assets'",
        "// touch-controls set.",
        "const Icon *find(std::string_view name);",
        "",
        "} // namespace touch_ui::embedded_icons",
        "",
    ]
    args.source.parent.mkdir(parents=True, exist_ok=True)
    args.source.write_text("\n".join(source))
    args.header.write_text("\n".join(header))
    return 0


if __name__ == "__main__":
    sys.exit(main())
